name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: CI
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'sbt'

      - name: Setup
        run: |
          PLATFORM="$(uname)"

          git submodule update --init
          cd webview

          if [ $PLATFORM == "Darwin" ]; then
            echo "It's a Mac"
            clang++ webview.cc -std=c++17 -framework WebKit -c
            ar rc webview.a webview.o
          else
            echo "It's a Linux"
            sudo apt update 
            sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev
            clang++ webview.cc -std=c++17 $(pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.0) -c
          fi

      - name: Compile examples
        run: sbt exampleBackend/nativeLink
